### ISSUE TITLE
大佬好

### ISSUE THREAD

**Issue by delicacyyy** [cw1997/inetutils#1]
想跟您讨论一下 因为cmake是跨平台的 所以想知道如果在windows下使用 不通过mingw或者wsl环境的话 可以直接使用吗

**Comment by cw1997** [comment]
您好，在 https://cmake.org/download/ 上下载Windows安装包即可，或者使用CLion打开该项目并即可，CLion默认使用cmake构建。但是该项目使用了raw socket（原始套接字）所以在windows下也许无法编译和使用

**Comment by delicacyyy** [comment]
![image](https://user-images.githubusercontent.com/11476249/126025305-7daa5eb9-d700-4947-9ae7-1311fea992f5.png)
我试了一下 clion好像不能debug了 断点都失效了 你感觉这是啥情况

**Comment by delicacyyy** [comment]
![image](https://user-images.githubusercontent.com/11476249/126027103-182cadca-c173-4027-b2d5-f1f380f6bf46.png)
哦 找到原因 改这里就行 不能用lldb

**Comment by delicacyyy** [comment]
![image](https://user-images.githubusercontent.com/11476249/126028549-7803a959-5529-400e-8394-18a9fbafea4d.png)
ping百度创建socket出现-1 提示Operation not permitted 是需要管理员运行吗

**Comment by cw1997** [comment]
是的，需要管理員權限運行，linux下加上sudo運行即可
